
package es.aragon.midas.ws.bdu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaBDU", targetNamespace = "http://ws.bdu.salud.aragon.es/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaBDU {


    /**
     * 
     * @param parameters
     * @return
     *     returns es.aragon.midas.ws.bdunew.FindResponseElement
     */
    @WebMethod(action = "http://ws.bdu.salud.aragon.es//find")
    @WebResult(name = "findResponseElement", targetNamespace = "http://ws.bdu.salud.aragon.es/types/", partName = "parameters")
    public FindResponseElement find(
        @WebParam(name = "findElement", targetNamespace = "http://ws.bdu.salud.aragon.es/types/", partName = "parameters")
        FindElement parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns es.aragon.midas.ws.bdunew.GetByCIAResponseElement
     */
    @WebMethod(action = "http://ws.bdu.salud.aragon.es//getByCIA")
    @WebResult(name = "getByCIAResponseElement", targetNamespace = "http://ws.bdu.salud.aragon.es/types/", partName = "parameters")
    public GetByCIAResponseElement getByCIA(
        @WebParam(name = "getByCIAElement", targetNamespace = "http://ws.bdu.salud.aragon.es/types/", partName = "parameters")
        GetByCIAElement parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns es.aragon.midas.ws.bdunew.GetByDNIResponseElement
     */
    @WebMethod(action = "http://ws.bdu.salud.aragon.es//getByDNI")
    @WebResult(name = "getByDNIResponseElement", targetNamespace = "http://ws.bdu.salud.aragon.es/types/", partName = "parameters")
    public GetByDNIResponseElement getByDNI(
        @WebParam(name = "getByDNIElement", targetNamespace = "http://ws.bdu.salud.aragon.es/types/", partName = "parameters")
        GetByDNIElement parameters);

}
