/**
 * AltovaException.java
 *
 * This file was generated by XMLSpy 2009 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.altova;


public class AltovaException extends RuntimeException {
	/**
	 * 
	 */
	private static final long serialVersionUID = 5908089750481637035L;
	protected Exception	innerException;
	protected String	message;

	public AltovaException(String text) {
		innerException = null;
		message = text;
	}

	public AltovaException(Exception other) {
		innerException = other;
		message = other.getMessage();
	}

	public String getMessage() {
		return message;
	}

	public Exception getInnerException() {
		return innerException;
	}
}
