////////////////////////////////////////////////////////////////////////
//
// scxml_typeinfo.java
//
// This file was generated by XMLSpy 2009 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


package es.aragon.midas.process.scxml;

import com.altova.typeinfo.*;



public class ScxmlTypeInfo
{
	// namespaces indices
	public static final int _altova_ni_xs = 0;
	public static final int _altova_ni = 1;
	public static final int _altova_ni_xml = 2;


	// typeinfo indices
	public static final int _altova_tif_xs = 0 ;
	public static final int _altova_ti_xs_altova_ENTITIES = _altova_tif_xs ;
	public static final int _altova_ti_xs_altova_ENTITY = 1 ;
	public static final int _altova_ti_xs_altova_ID = 2 ;
	public static final int _altova_ti_xs_altova_IDREF = 3 ;
	public static final int _altova_ti_xs_altova_IDREFS = 4 ;
	public static final int _altova_ti_xs_altova_NCName = 5 ;
	public static final int _altova_ti_xs_altova_NMTOKEN = 6 ;
	public static final int _altova_ti_xs_altova_NMTOKENS = 7 ;
	public static final int _altova_ti_xs_altova_NOTATION = 8 ;
	public static final int _altova_ti_xs_altova_Name = 9 ;
	public static final int _altova_ti_xs_altova_QName = 10 ;
	public static final int _altova_ti_xs_altova_anySimpleType = 11 ;
	public static final int _altova_ti_xs_altova_anyType = 12 ;
	public static final int _altova_ti_xs_altova_anyURI = 13 ;
	public static final int _altova_ti_xs_altova_base64Binary = 14 ;
	public static final int _altova_ti_xs_altova_boolean2 = 15 ;
	public static final int _altova_ti_xs_altova_byte2 = 16 ;
	public static final int _altova_ti_xs_altova_date = 17 ;
	public static final int _altova_ti_xs_altova_dateTime = 18 ;
	public static final int _altova_ti_xs_altova_decimal = 19 ;
	public static final int _altova_ti_xs_altova_double2 = 20 ;
	public static final int _altova_ti_xs_altova_duration = 21 ;
	public static final int _altova_ti_xs_altova_float2 = 22 ;
	public static final int _altova_ti_xs_altova_gDay = 23 ;
	public static final int _altova_ti_xs_altova_gMonth = 24 ;
	public static final int _altova_ti_xs_altova_gMonthDay = 25 ;
	public static final int _altova_ti_xs_altova_gYear = 26 ;
	public static final int _altova_ti_xs_altova_gYearMonth = 27 ;
	public static final int _altova_ti_xs_altova_hexBinary = 28 ;
	public static final int _altova_ti_xs_altova_int2 = 29 ;
	public static final int _altova_ti_xs_altova_integer = 30 ;
	public static final int _altova_ti_xs_altova_language = 31 ;
	public static final int _altova_ti_xs_altova_long2 = 32 ;
	public static final int _altova_ti_xs_altova_negativeInteger = 33 ;
	public static final int _altova_ti_xs_altova_nonNegativeInteger = 34 ;
	public static final int _altova_ti_xs_altova_nonPositiveInteger = 35 ;
	public static final int _altova_ti_xs_altova_normalizedString = 36 ;
	public static final int _altova_ti_xs_altova_positiveInteger = 37 ;
	public static final int _altova_ti_xs_altova_short2 = 38 ;
	public static final int _altova_ti_xs_altova_string2 = 39 ;
	public static final int _altova_ti_xs_altova_time = 40 ;
	public static final int _altova_ti_xs_altova_token = 41 ;
	public static final int _altova_ti_xs_altova_unsignedByte = 42 ;
	public static final int _altova_ti_xs_altova_unsignedInt = 43 ;
	public static final int _altova_ti_xs_altova_unsignedLong = 44 ;
	public static final int _altova_ti_xs_altova_unsignedShort = 45 ;
	public static final int _altova_til_xs = 46 ;

	public static final int _altova_tif = _altova_til_xs;
	public static final int _altova_ti_altova_AssignType_datatype = _altova_tif ;
	public static final int _altova_ti_altova_Binding_datatype = 47 ;
	public static final int _altova_ti_altova_Boolean_datatype = 48 ;
	public static final int _altova_ti_altova_CondLang_datatype = 49 ;
	public static final int _altova_ti_altova_Duration_datatype = 50 ;
	public static final int _altova_ti_altova_EventType_datatype = 51 ;
	public static final int _altova_ti_altova_EventTypes_datatype = 52 ;
	public static final int _altova_ti_altova_Exmode_datatype = 53 ;
	public static final int _altova_ti_altova_HistoryType_datatype = 54 ;
	public static final int _altova_ti_altova_Integer_datatype = 55 ;
	public static final int _altova_ti_altova_LocLang_datatype = 56 ;
	public static final int _altova_ti_altova_TransitionType_datatype = 57 ;
	public static final int _altova_ti_altova_URI_datatype = 58 ;
	public static final int _altova_ti_altova_ValueLang_datatype = 59 ;
	public static final int _altova_ti_altova_scxml_assign_type = 60 ;
	public static final int _altova_ti_altova_scxml_cancel_type = 61 ;
	public static final int _altova_ti_altova_scxml_content_type = 62 ;
	public static final int _altova_ti_altova_scxml_data_type = 63 ;
	public static final int _altova_ti_altova_scxml_datamodel_type = 64 ;
	public static final int _altova_ti_altova_scxml_donedata_type = 65 ;
	public static final int _altova_ti_altova_scxml_else_type = 66 ;
	public static final int _altova_ti_altova_scxml_elseif_type = 67 ;
	public static final int _altova_ti_altova_scxml_final_type = 68 ;
	public static final int _altova_ti_altova_scxml_finalize_type = 69 ;
	public static final int _altova_ti_altova_scxml_foreach_type = 70 ;
	public static final int _altova_ti_altova_scxml_history_type = 71 ;
	public static final int _altova_ti_altova_scxml_if_type = 72 ;
	public static final int _altova_ti_altova_scxml_initial_type = 73 ;
	public static final int _altova_ti_altova_scxml_invoke_type = 74 ;
	public static final int _altova_ti_altova_scxml_log_type = 75 ;
	public static final int _altova_ti_altova_scxml_onentry_type = 76 ;
	public static final int _altova_ti_altova_scxml_onexit_type = 77 ;
	public static final int _altova_ti_altova_scxml_parallel_type = 78 ;
	public static final int _altova_ti_altova_scxml_param_type = 79 ;
	public static final int _altova_ti_altova_scxml_raise_type = 80 ;
	public static final int _altova_ti_altova_scxml_script_type = 81 ;
	public static final int _altova_ti_altova_scxml_scxml_type = 82 ;
	public static final int _altova_ti_altova_scxml_send_type = 83 ;
	public static final int _altova_ti_altova_scxml_state_type = 84 ;
	public static final int _altova_ti_altova_scxml_transition_type = 85 ;
	public static final int _altova_ti_altova_scxml2 = 86 ;
	public static final int _altova_til = 87 ;

	public static final int _altova_tif_xml = _altova_til;
	public static final int _altova_til_xml = _altova_tif_xml ;



	// memberinfo indices

	public static class _altova_mi_xs_altova_ENTITIES {
		public static final int begin = 0 ;
		public static final int end = _altova_mi_xs_altova_ENTITIES.begin ;
	};


	public static class _altova_mi_xs_altova_ENTITY {
		public static final int begin = _altova_mi_xs_altova_ENTITIES.end ;
		public static final int end = _altova_mi_xs_altova_ENTITY.begin ;
	};


	public static class _altova_mi_xs_altova_ID {
		public static final int begin = _altova_mi_xs_altova_ENTITY.end ;
		public static final int end = _altova_mi_xs_altova_ID.begin ;
	};


	public static class _altova_mi_xs_altova_IDREF {
		public static final int begin = _altova_mi_xs_altova_ID.end ;
		public static final int end = _altova_mi_xs_altova_IDREF.begin ;
	};


	public static class _altova_mi_xs_altova_IDREFS {
		public static final int begin = _altova_mi_xs_altova_IDREF.end ;
		public static final int end = _altova_mi_xs_altova_IDREFS.begin ;
	};


	public static class _altova_mi_xs_altova_NCName {
		public static final int begin = _altova_mi_xs_altova_IDREFS.end ;
		public static final int end = _altova_mi_xs_altova_NCName.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKEN {
		public static final int begin = _altova_mi_xs_altova_NCName.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKEN.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKENS {
		public static final int begin = _altova_mi_xs_altova_NMTOKEN.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKENS.begin ;
	};


	public static class _altova_mi_xs_altova_NOTATION {
		public static final int begin = _altova_mi_xs_altova_NMTOKENS.end ;
		public static final int end = _altova_mi_xs_altova_NOTATION.begin ;
	};


	public static class _altova_mi_xs_altova_Name {
		public static final int begin = _altova_mi_xs_altova_NOTATION.end ;
		public static final int end = _altova_mi_xs_altova_Name.begin ;
	};


	public static class _altova_mi_xs_altova_QName {
		public static final int begin = _altova_mi_xs_altova_Name.end ;
		public static final int end = _altova_mi_xs_altova_QName.begin ;
	};


	public static class _altova_mi_xs_altova_anySimpleType {
		public static final int begin = _altova_mi_xs_altova_QName.end ;
		public static final int end = _altova_mi_xs_altova_anySimpleType.begin ;
	};


	public static class _altova_mi_xs_altova_anyType {
		public static final int begin = _altova_mi_xs_altova_anySimpleType.end ;
		public static final int _unnamed = _altova_mi_xs_altova_anyType.begin ;
		public static final int end = 1 ;
	};


	public static class _altova_mi_xs_altova_anyURI {
		public static final int begin = _altova_mi_xs_altova_anyType.end ;
		public static final int end = _altova_mi_xs_altova_anyURI.begin ;
	};


	public static class _altova_mi_xs_altova_base64Binary {
		public static final int begin = _altova_mi_xs_altova_anyURI.end ;
		public static final int end = _altova_mi_xs_altova_base64Binary.begin ;
	};


	public static class _altova_mi_xs_altova_boolean2 {
		public static final int begin = _altova_mi_xs_altova_base64Binary.end ;
		public static final int end = _altova_mi_xs_altova_boolean2.begin ;
	};


	public static class _altova_mi_xs_altova_byte2 {
		public static final int begin = _altova_mi_xs_altova_boolean2.end ;
		public static final int end = _altova_mi_xs_altova_byte2.begin ;
	};


	public static class _altova_mi_xs_altova_date {
		public static final int begin = _altova_mi_xs_altova_byte2.end ;
		public static final int end = _altova_mi_xs_altova_date.begin ;
	};


	public static class _altova_mi_xs_altova_dateTime {
		public static final int begin = _altova_mi_xs_altova_date.end ;
		public static final int end = _altova_mi_xs_altova_dateTime.begin ;
	};


	public static class _altova_mi_xs_altova_decimal {
		public static final int begin = _altova_mi_xs_altova_dateTime.end ;
		public static final int end = _altova_mi_xs_altova_decimal.begin ;
	};


	public static class _altova_mi_xs_altova_double2 {
		public static final int begin = _altova_mi_xs_altova_decimal.end ;
		public static final int end = _altova_mi_xs_altova_double2.begin ;
	};


	public static class _altova_mi_xs_altova_duration {
		public static final int begin = _altova_mi_xs_altova_double2.end ;
		public static final int end = _altova_mi_xs_altova_duration.begin ;
	};


	public static class _altova_mi_xs_altova_float2 {
		public static final int begin = _altova_mi_xs_altova_duration.end ;
		public static final int end = _altova_mi_xs_altova_float2.begin ;
	};


	public static class _altova_mi_xs_altova_gDay {
		public static final int begin = _altova_mi_xs_altova_float2.end ;
		public static final int end = _altova_mi_xs_altova_gDay.begin ;
	};


	public static class _altova_mi_xs_altova_gMonth {
		public static final int begin = _altova_mi_xs_altova_gDay.end ;
		public static final int end = _altova_mi_xs_altova_gMonth.begin ;
	};


	public static class _altova_mi_xs_altova_gMonthDay {
		public static final int begin = _altova_mi_xs_altova_gMonth.end ;
		public static final int end = _altova_mi_xs_altova_gMonthDay.begin ;
	};


	public static class _altova_mi_xs_altova_gYear {
		public static final int begin = _altova_mi_xs_altova_gMonthDay.end ;
		public static final int end = _altova_mi_xs_altova_gYear.begin ;
	};


	public static class _altova_mi_xs_altova_gYearMonth {
		public static final int begin = _altova_mi_xs_altova_gYear.end ;
		public static final int end = _altova_mi_xs_altova_gYearMonth.begin ;
	};


	public static class _altova_mi_xs_altova_hexBinary {
		public static final int begin = _altova_mi_xs_altova_gYearMonth.end ;
		public static final int end = _altova_mi_xs_altova_hexBinary.begin ;
	};


	public static class _altova_mi_xs_altova_int2 {
		public static final int begin = _altova_mi_xs_altova_hexBinary.end ;
		public static final int end = _altova_mi_xs_altova_int2.begin ;
	};


	public static class _altova_mi_xs_altova_integer {
		public static final int begin = _altova_mi_xs_altova_int2.end ;
		public static final int end = _altova_mi_xs_altova_integer.begin ;
	};


	public static class _altova_mi_xs_altova_language {
		public static final int begin = _altova_mi_xs_altova_integer.end ;
		public static final int end = _altova_mi_xs_altova_language.begin ;
	};


	public static class _altova_mi_xs_altova_long2 {
		public static final int begin = _altova_mi_xs_altova_language.end ;
		public static final int end = _altova_mi_xs_altova_long2.begin ;
	};


	public static class _altova_mi_xs_altova_negativeInteger {
		public static final int begin = _altova_mi_xs_altova_long2.end ;
		public static final int end = _altova_mi_xs_altova_negativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonNegativeInteger {
		public static final int begin = _altova_mi_xs_altova_negativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonNegativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonPositiveInteger {
		public static final int begin = _altova_mi_xs_altova_nonNegativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonPositiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_normalizedString {
		public static final int begin = _altova_mi_xs_altova_nonPositiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_normalizedString.begin ;
	};


	public static class _altova_mi_xs_altova_positiveInteger {
		public static final int begin = _altova_mi_xs_altova_normalizedString.end ;
		public static final int end = _altova_mi_xs_altova_positiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_short2 {
		public static final int begin = _altova_mi_xs_altova_positiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_short2.begin ;
	};


	public static class _altova_mi_xs_altova_string2 {
		public static final int begin = _altova_mi_xs_altova_short2.end ;
		public static final int end = _altova_mi_xs_altova_string2.begin ;
	};


	public static class _altova_mi_xs_altova_time {
		public static final int begin = _altova_mi_xs_altova_string2.end ;
		public static final int end = _altova_mi_xs_altova_time.begin ;
	};


	public static class _altova_mi_xs_altova_token {
		public static final int begin = _altova_mi_xs_altova_time.end ;
		public static final int end = _altova_mi_xs_altova_token.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedByte {
		public static final int begin = _altova_mi_xs_altova_token.end ;
		public static final int end = _altova_mi_xs_altova_unsignedByte.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedInt {
		public static final int begin = _altova_mi_xs_altova_unsignedByte.end ;
		public static final int end = _altova_mi_xs_altova_unsignedInt.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedLong {
		public static final int begin = _altova_mi_xs_altova_unsignedInt.end ;
		public static final int end = _altova_mi_xs_altova_unsignedLong.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedShort {
		public static final int begin = _altova_mi_xs_altova_unsignedLong.end ;
		public static final int end = _altova_mi_xs_altova_unsignedShort.begin ;
	};


	public static class _altova_mi_altova_AssignType_datatype {
		public static final int begin = _altova_mi_xs_altova_unsignedShort.end ;
		public static final int end = _altova_mi_altova_AssignType_datatype.begin ;
	};


	public static class _altova_mi_altova_Binding_datatype {
		public static final int begin = _altova_mi_altova_AssignType_datatype.end ;
		public static final int end = _altova_mi_altova_Binding_datatype.begin ;
	};


	public static class _altova_mi_altova_Boolean_datatype {
		public static final int begin = _altova_mi_altova_Binding_datatype.end ;
		public static final int end = _altova_mi_altova_Boolean_datatype.begin ;
	};


	public static class _altova_mi_altova_CondLang_datatype {
		public static final int begin = _altova_mi_altova_Boolean_datatype.end ;
		public static final int end = _altova_mi_altova_CondLang_datatype.begin ;
	};


	public static class _altova_mi_altova_Duration_datatype {
		public static final int begin = _altova_mi_altova_CondLang_datatype.end ;
		public static final int end = _altova_mi_altova_Duration_datatype.begin ;
	};


	public static class _altova_mi_altova_EventType_datatype {
		public static final int begin = _altova_mi_altova_Duration_datatype.end ;
		public static final int end = _altova_mi_altova_EventType_datatype.begin ;
	};


	public static class _altova_mi_altova_EventTypes_datatype {
		public static final int begin = _altova_mi_altova_EventType_datatype.end ;
		public static final int end = _altova_mi_altova_EventTypes_datatype.begin ;
	};


	public static class _altova_mi_altova_Exmode_datatype {
		public static final int begin = _altova_mi_altova_EventTypes_datatype.end ;
		public static final int end = _altova_mi_altova_Exmode_datatype.begin ;
	};


	public static class _altova_mi_altova_HistoryType_datatype {
		public static final int begin = _altova_mi_altova_Exmode_datatype.end ;
		public static final int end = _altova_mi_altova_HistoryType_datatype.begin ;
	};


	public static class _altova_mi_altova_Integer_datatype {
		public static final int begin = _altova_mi_altova_HistoryType_datatype.end ;
		public static final int end = _altova_mi_altova_Integer_datatype.begin ;
	};


	public static class _altova_mi_altova_LocLang_datatype {
		public static final int begin = _altova_mi_altova_Integer_datatype.end ;
		public static final int end = _altova_mi_altova_LocLang_datatype.begin ;
	};


	public static class _altova_mi_altova_TransitionType_datatype {
		public static final int begin = _altova_mi_altova_LocLang_datatype.end ;
		public static final int end = _altova_mi_altova_TransitionType_datatype.begin ;
	};


	public static class _altova_mi_altova_URI_datatype {
		public static final int begin = _altova_mi_altova_TransitionType_datatype.end ;
		public static final int end = _altova_mi_altova_URI_datatype.begin ;
	};


	public static class _altova_mi_altova_ValueLang_datatype {
		public static final int begin = _altova_mi_altova_URI_datatype.end ;
		public static final int end = _altova_mi_altova_ValueLang_datatype.begin ;
	};


	public static class _altova_mi_altova_scxml_assign_type {
		public static final int begin = _altova_mi_altova_ValueLang_datatype.end ;
		public static final int _unnamed = _altova_mi_altova_scxml_assign_type.begin ;
		public static final int _location = 2 ;
		public static final int _expr = 3 ;
		public static final int _type = 4 ;
		public static final int _attr = 5 ;
		public static final int end = 6 ;
	};


	public static class _altova_mi_altova_scxml_cancel_type {
		public static final int begin = _altova_mi_altova_scxml_assign_type.end ;
		public static final int _sendid = _altova_mi_altova_scxml_cancel_type.begin ;
		public static final int _sendidexpr = 7 ;
		public static final int end = 8 ;
	};


	public static class _altova_mi_altova_scxml_content_type {
		public static final int begin = _altova_mi_altova_scxml_cancel_type.end ;
		public static final int _unnamed = _altova_mi_altova_scxml_content_type.begin ;
		public static final int _expr = 9 ;
		public static final int end = 10 ;
	};


	public static class _altova_mi_altova_scxml_data_type {
		public static final int begin = _altova_mi_altova_scxml_content_type.end ;
		public static final int _unnamed = _altova_mi_altova_scxml_data_type.begin ;
		public static final int _id = 11 ;
		public static final int _src = 12 ;
		public static final int _expr = 13 ;
		public static final int end = 14 ;
	};


	public static class _altova_mi_altova_scxml_datamodel_type {
		public static final int begin = _altova_mi_altova_scxml_data_type.end ;
		public static final int _data = _altova_mi_altova_scxml_datamodel_type.begin ;
		public static final int end = 15 ;
	};


	public static class _altova_mi_altova_scxml_donedata_type {
		public static final int begin = _altova_mi_altova_scxml_datamodel_type.end ;
		public static final int _content = _altova_mi_altova_scxml_donedata_type.begin ;
		public static final int _param = 16 ;
		public static final int end = 17 ;
	};


	public static class _altova_mi_altova_scxml_else_type {
		public static final int begin = _altova_mi_altova_scxml_donedata_type.end ;
		public static final int end = _altova_mi_altova_scxml_else_type.begin ;
	};


	public static class _altova_mi_altova_scxml_elseif_type {
		public static final int begin = _altova_mi_altova_scxml_else_type.end ;
		public static final int _cond = _altova_mi_altova_scxml_elseif_type.begin ;
		public static final int end = 18 ;
	};


	public static class _altova_mi_altova_scxml_final_type {
		public static final int begin = _altova_mi_altova_scxml_elseif_type.end ;
		public static final int _id = _altova_mi_altova_scxml_final_type.begin ;
		public static final int _onentry = 19 ;
		public static final int _onexit = 20 ;
		public static final int _donedata = 21 ;
		public static final int end = 22 ;
	};


	public static class _altova_mi_altova_scxml_finalize_type {
		public static final int begin = _altova_mi_altova_scxml_final_type.end ;
		public static final int _raise = _altova_mi_altova_scxml_finalize_type.begin ;
		public static final int _if2 = 23 ;
		public static final int _foreach = 24 ;
		public static final int _send = 25 ;
		public static final int _script = 26 ;
		public static final int _assign = 27 ;
		public static final int _log = 28 ;
		public static final int _cancel = 29 ;
		public static final int end = 30 ;
	};


	public static class _altova_mi_altova_scxml_foreach_type {
		public static final int begin = _altova_mi_altova_scxml_finalize_type.end ;
		public static final int _array = _altova_mi_altova_scxml_foreach_type.begin ;
		public static final int _item = 31 ;
		public static final int _index = 32 ;
		public static final int _raise = 33 ;
		public static final int _if2 = 34 ;
		public static final int _foreach = 35 ;
		public static final int _send = 36 ;
		public static final int _script = 37 ;
		public static final int _assign = 38 ;
		public static final int _log = 39 ;
		public static final int _cancel = 40 ;
		public static final int end = 41 ;
	};


	public static class _altova_mi_altova_scxml_history_type {
		public static final int begin = _altova_mi_altova_scxml_foreach_type.end ;
		public static final int _id = _altova_mi_altova_scxml_history_type.begin ;
		public static final int _type = 42 ;
		public static final int _transition = 43 ;
		public static final int end = 44 ;
	};


	public static class _altova_mi_altova_scxml_if_type {
		public static final int begin = _altova_mi_altova_scxml_history_type.end ;
		public static final int _cond = _altova_mi_altova_scxml_if_type.begin ;
		public static final int _raise = 45 ;
		public static final int _if2 = 46 ;
		public static final int _foreach = 47 ;
		public static final int _send = 48 ;
		public static final int _script = 49 ;
		public static final int _assign = 50 ;
		public static final int _log = 51 ;
		public static final int _cancel = 52 ;
		public static final int _elseif = 53 ;
		public static final int _else2 = 54 ;
		public static final int end = 55 ;
	};


	public static class _altova_mi_altova_scxml_initial_type {
		public static final int begin = _altova_mi_altova_scxml_if_type.end ;
		public static final int _transition = _altova_mi_altova_scxml_initial_type.begin ;
		public static final int end = 56 ;
	};


	public static class _altova_mi_altova_scxml_invoke_type {
		public static final int begin = _altova_mi_altova_scxml_initial_type.end ;
		public static final int _type = _altova_mi_altova_scxml_invoke_type.begin ;
		public static final int _typeexpr = 57 ;
		public static final int _src = 58 ;
		public static final int _srcexpr = 59 ;
		public static final int _id = 60 ;
		public static final int _idlocation = 61 ;
		public static final int _namelist = 62 ;
		public static final int _autoforward = 63 ;
		public static final int _content = 64 ;
		public static final int _param = 65 ;
		public static final int _finalize = 66 ;
		public static final int end = 67 ;
	};


	public static class _altova_mi_altova_scxml_log_type {
		public static final int begin = _altova_mi_altova_scxml_invoke_type.end ;
		public static final int _label = _altova_mi_altova_scxml_log_type.begin ;
		public static final int _expr = 68 ;
		public static final int end = 69 ;
	};


	public static class _altova_mi_altova_scxml_onentry_type {
		public static final int begin = _altova_mi_altova_scxml_log_type.end ;
		public static final int _raise = _altova_mi_altova_scxml_onentry_type.begin ;
		public static final int _if2 = 70 ;
		public static final int _foreach = 71 ;
		public static final int _send = 72 ;
		public static final int _script = 73 ;
		public static final int _assign = 74 ;
		public static final int _log = 75 ;
		public static final int _cancel = 76 ;
		public static final int end = 77 ;
	};


	public static class _altova_mi_altova_scxml_onexit_type {
		public static final int begin = _altova_mi_altova_scxml_onentry_type.end ;
		public static final int _raise = _altova_mi_altova_scxml_onexit_type.begin ;
		public static final int _if2 = 78 ;
		public static final int _foreach = 79 ;
		public static final int _send = 80 ;
		public static final int _script = 81 ;
		public static final int _assign = 82 ;
		public static final int _log = 83 ;
		public static final int _cancel = 84 ;
		public static final int end = 85 ;
	};


	public static class _altova_mi_altova_scxml_parallel_type {
		public static final int begin = _altova_mi_altova_scxml_onexit_type.end ;
		public static final int _id = _altova_mi_altova_scxml_parallel_type.begin ;
		public static final int _onentry = 86 ;
		public static final int _onexit = 87 ;
		public static final int _transition = 88 ;
		public static final int _state = 89 ;
		public static final int _parallel = 90 ;
		public static final int _history = 91 ;
		public static final int _datamodel = 92 ;
		public static final int _invoke = 93 ;
		public static final int end = 94 ;
	};


	public static class _altova_mi_altova_scxml_param_type {
		public static final int begin = _altova_mi_altova_scxml_parallel_type.end ;
		public static final int _name = _altova_mi_altova_scxml_param_type.begin ;
		public static final int _expr = 95 ;
		public static final int _location = 96 ;
		public static final int end = 97 ;
	};


	public static class _altova_mi_altova_scxml_raise_type {
		public static final int begin = _altova_mi_altova_scxml_param_type.end ;
		public static final int _event = _altova_mi_altova_scxml_raise_type.begin ;
		public static final int end = 98 ;
	};


	public static class _altova_mi_altova_scxml_script_type {
		public static final int begin = _altova_mi_altova_scxml_raise_type.end ;
		public static final int _unnamed = _altova_mi_altova_scxml_script_type.begin ;
		public static final int _src = 99 ;
		public static final int end = 100 ;
	};


	public static class _altova_mi_altova_scxml_scxml_type {
		public static final int begin = _altova_mi_altova_scxml_script_type.end ;
		public static final int _initial = _altova_mi_altova_scxml_scxml_type.begin ;
		public static final int _name = 101 ;
		public static final int _version = 102 ;
		public static final int _datamodel = 103 ;
		public static final int _binding = 104 ;
		public static final int _exmode = 105 ;
		public static final int _state = 106 ;
		public static final int _parallel = 107 ;
		public static final int _final2 = 108 ;
		public static final int _datamodel2 = 109 ;
		public static final int _script = 110 ;
		public static final int end = 111 ;
	};


	public static class _altova_mi_altova_scxml_send_type {
		public static final int begin = _altova_mi_altova_scxml_scxml_type.end ;
		public static final int _event = _altova_mi_altova_scxml_send_type.begin ;
		public static final int _eventexpr = 112 ;
		public static final int _target = 113 ;
		public static final int _targetexpr = 114 ;
		public static final int _type = 115 ;
		public static final int _typeexpr = 116 ;
		public static final int _id = 117 ;
		public static final int _idlocation = 118 ;
		public static final int _delay = 119 ;
		public static final int _delayexpr = 120 ;
		public static final int _namelist = 121 ;
		public static final int _content = 122 ;
		public static final int _param = 123 ;
		public static final int end = 124 ;
	};


	public static class _altova_mi_altova_scxml_state_type {
		public static final int begin = _altova_mi_altova_scxml_send_type.end ;
		public static final int _id = _altova_mi_altova_scxml_state_type.begin ;
		public static final int _initial = 125 ;
		public static final int _onentry = 126 ;
		public static final int _onexit = 127 ;
		public static final int _transition = 128 ;
		public static final int _initial2 = 129 ;
		public static final int _state = 130 ;
		public static final int _parallel = 131 ;
		public static final int _final2 = 132 ;
		public static final int _history = 133 ;
		public static final int _datamodel = 134 ;
		public static final int _invoke = 135 ;
		public static final int end = 136 ;
	};


	public static class _altova_mi_altova_scxml_transition_type {
		public static final int begin = _altova_mi_altova_scxml_state_type.end ;
		public static final int _event = _altova_mi_altova_scxml_transition_type.begin ;
		public static final int _cond = 137 ;
		public static final int _target = 138 ;
		public static final int _type = 139 ;
		public static final int _raise = 140 ;
		public static final int _if2 = 141 ;
		public static final int _foreach = 142 ;
		public static final int _send = 143 ;
		public static final int _script = 144 ;
		public static final int _assign = 145 ;
		public static final int _log = 146 ;
		public static final int _cancel = 147 ;
		public static final int end = 148 ;
	};


	public static class _altova_mi_altova_scxml2 {
		public static final int begin = _altova_mi_altova_scxml_transition_type.end ;
		public static final int _assign = _altova_mi_altova_scxml2.begin ;
		public static final int _cancel = 149 ;
		public static final int _content = 150 ;
		public static final int _data = 151 ;
		public static final int _datamodel = 152 ;
		public static final int _donedata = 153 ;
		public static final int _else2 = 154 ;
		public static final int _elseif = 155 ;
		public static final int _final2 = 156 ;
		public static final int _finalize = 157 ;
		public static final int _foreach = 158 ;
		public static final int _history = 159 ;
		public static final int _if2 = 160 ;
		public static final int _initial = 161 ;
		public static final int _invoke = 162 ;
		public static final int _log = 163 ;
		public static final int _onentry = 164 ;
		public static final int _onexit = 165 ;
		public static final int _parallel = 166 ;
		public static final int _param = 167 ;
		public static final int _raise = 168 ;
		public static final int _script = 169 ;
		public static final int _scxml3 = 170 ;
		public static final int _send = 171 ;
		public static final int _state = 172 ;
		public static final int _transition = 173 ;
		public static final int end = 174 ;
	};

	

	public static class InfoBinder implements InfoBinderInterface
	{
		public NamespaceInfo[] getNamespaces() {return namespaces;}
		public TypeInfo[] getTypes() {return types;}
		public MemberInfo[] getMembers() {return members;}
	}
	
	public static final InfoBinderInterface binder = new InfoBinder();

	// Array of all namespaces with pointers to types:
	private static final NamespaceInfo namespaces[] = 
	{
		new NamespaceInfo(binder, "http://www.w3.org/2001/XMLSchema", "xs", _altova_tif_xs, _altova_til_xs),
		new NamespaceInfo(binder, "http://www.w3.org/2005/07/scxml", "", _altova_tif, _altova_til),
		new NamespaceInfo(binder, "http://www.w3.org/XML/1998/namespace", "xml", _altova_tif_xml, _altova_til_xml),
	};

	
// Array of all types with pointers to members:
	private static final TypeInfo types[] = new TypeInfoCreator().createTypes(binder);

	private static class TypeInfoCreator
	{
		private void initTypes0(InfoBinderInterface binder, TypeInfo[] types) {
			types[0] = new TypeInfo( binder, _altova_ni_xs, "ENTITIES", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_ENTITIES.begin, _altova_mi_xs_altova_ENTITIES.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[1] = new TypeInfo( binder, _altova_ni_xs, "ENTITY", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ENTITY.begin, _altova_mi_xs_altova_ENTITY.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[2] = new TypeInfo( binder, _altova_ni_xs, "ID", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ID.begin, _altova_mi_xs_altova_ID.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[3] = new TypeInfo( binder, _altova_ni_xs, "IDREF", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_IDREF.begin, _altova_mi_xs_altova_IDREF.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[4] = new TypeInfo( binder, _altova_ni_xs, "IDREFS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_IDREFS.begin, _altova_mi_xs_altova_IDREFS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[5] = new TypeInfo( binder, _altova_ni_xs, "NCName", _altova_ti_xs_altova_Name, _altova_mi_xs_altova_NCName.begin, _altova_mi_xs_altova_NCName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "[\\i-[:]][\\c-[:]]*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[6] = new TypeInfo( binder, _altova_ni_xs, "NMTOKEN", _altova_ti_xs_altova_token, _altova_mi_xs_altova_NMTOKEN.begin, _altova_mi_xs_altova_NMTOKEN.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[7] = new TypeInfo( binder, _altova_ni_xs, "NMTOKENS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NMTOKENS.begin, _altova_mi_xs_altova_NMTOKENS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[8] = new TypeInfo( binder, _altova_ni_xs, "NOTATION", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NOTATION.begin, _altova_mi_xs_altova_NOTATION.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[9] = new TypeInfo( binder, _altova_ni_xs, "Name", _altova_ti_xs_altova_token, _altova_mi_xs_altova_Name.begin, _altova_mi_xs_altova_Name.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\i\\c*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[10] = new TypeInfo( binder, _altova_ni_xs, "QName", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_QName.begin, _altova_mi_xs_altova_QName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[11] = new TypeInfo( binder, _altova_ni_xs, "anySimpleType", 0, _altova_mi_xs_altova_anySimpleType.begin, _altova_mi_xs_altova_anySimpleType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[12] = new TypeInfo( binder, _altova_ni_xs, "anyType", 0, _altova_mi_xs_altova_anyType.begin, _altova_mi_xs_altova_anyType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[13] = new TypeInfo( binder, _altova_ni_xs, "anyURI", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_anyURI.begin, _altova_mi_xs_altova_anyURI.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[14] = new TypeInfo( binder, _altova_ni_xs, "base64Binary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_base64Binary.begin, _altova_mi_xs_altova_base64Binary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[15] = new TypeInfo( binder, _altova_ni_xs, "boolean", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_boolean2.begin, _altova_mi_xs_altova_boolean2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[16] = new TypeInfo( binder, _altova_ni_xs, "byte", _altova_ti_xs_altova_short2, _altova_mi_xs_altova_byte2.begin, _altova_mi_xs_altova_byte2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-128", 0 ), 
					new FacetInfo (null, "maxInclusive", "127", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[17] = new TypeInfo( binder, _altova_ni_xs, "date", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_date.begin, _altova_mi_xs_altova_date.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DateFormatter );
			types[18] = new TypeInfo( binder, _altova_ni_xs, "dateTime", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_dateTime.begin, _altova_mi_xs_altova_dateTime.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DateTimeFormatter );
			types[19] = new TypeInfo( binder, _altova_ni_xs, "decimal", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_decimal.begin, _altova_mi_xs_altova_decimal.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DecimalFormatter );
			types[20] = new TypeInfo( binder, _altova_ni_xs, "double", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_double2.begin, _altova_mi_xs_altova_double2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DoubleFormatter );
			types[21] = new TypeInfo( binder, _altova_ni_xs, "duration", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_duration.begin, _altova_mi_xs_altova_duration.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DurationFormatter );
			types[22] = new TypeInfo( binder, _altova_ni_xs, "float", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_float2.begin, _altova_mi_xs_altova_float2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DoubleFormatter );
			types[23] = new TypeInfo( binder, _altova_ni_xs, "gDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gDay.begin, _altova_mi_xs_altova_gDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GDayFormatter );
			types[24] = new TypeInfo( binder, _altova_ni_xs, "gMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonth.begin, _altova_mi_xs_altova_gMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GMonthFormatter );
			types[25] = new TypeInfo( binder, _altova_ni_xs, "gMonthDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonthDay.begin, _altova_mi_xs_altova_gMonthDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GMonthDayFormatter );
			types[26] = new TypeInfo( binder, _altova_ni_xs, "gYear", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYear.begin, _altova_mi_xs_altova_gYear.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GYearFormatter );
			types[27] = new TypeInfo( binder, _altova_ni_xs, "gYearMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYearMonth.begin, _altova_mi_xs_altova_gYearMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GYearMonthFormatter );
			types[28] = new TypeInfo( binder, _altova_ni_xs, "hexBinary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_hexBinary.begin, _altova_mi_xs_altova_hexBinary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.HexBinaryFormatter );
			types[29] = new TypeInfo( binder, _altova_ni_xs, "int", _altova_ti_xs_altova_long2, _altova_mi_xs_altova_int2.begin, _altova_mi_xs_altova_int2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-2147483648", 0 ), 
					new FacetInfo (null, "maxInclusive", "2147483647", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[30] = new TypeInfo( binder, _altova_ni_xs, "integer", _altova_ti_xs_altova_decimal, _altova_mi_xs_altova_integer.begin, _altova_mi_xs_altova_integer.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[31] = new TypeInfo( binder, _altova_ni_xs, "language", _altova_ti_xs_altova_token, _altova_mi_xs_altova_language.begin, _altova_mi_xs_altova_language.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[32] = new TypeInfo( binder, _altova_ni_xs, "long", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_long2.begin, _altova_mi_xs_altova_long2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-9223372036854775808", 0 ), 
					new FacetInfo (null, "maxInclusive", "9223372036854775807", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[33] = new TypeInfo( binder, _altova_ni_xs, "negativeInteger", _altova_ti_xs_altova_nonPositiveInteger, _altova_mi_xs_altova_negativeInteger.begin, _altova_mi_xs_altova_negativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "-1", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[34] = new TypeInfo( binder, _altova_ni_xs, "nonNegativeInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonNegativeInteger.begin, _altova_mi_xs_altova_nonNegativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "0", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[35] = new TypeInfo( binder, _altova_ni_xs, "nonPositiveInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonPositiveInteger.begin, _altova_mi_xs_altova_nonPositiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "0", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[36] = new TypeInfo( binder, _altova_ni_xs, "normalizedString", _altova_ti_xs_altova_string2, _altova_mi_xs_altova_normalizedString.begin, _altova_mi_xs_altova_normalizedString.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "replace", 0 ),
				},
				WhitespaceType.Whitespace_Replace, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[37] = new TypeInfo( binder, _altova_ni_xs, "positiveInteger", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_positiveInteger.begin, _altova_mi_xs_altova_positiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "1", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[38] = new TypeInfo( binder, _altova_ni_xs, "short", _altova_ti_xs_altova_int2, _altova_mi_xs_altova_short2.begin, _altova_mi_xs_altova_short2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-32768", 0 ), 
					new FacetInfo (null, "maxInclusive", "32767", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[39] = new TypeInfo( binder, _altova_ni_xs, "string", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_string2.begin, _altova_mi_xs_altova_string2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "preserve", 0 ),
				},
				WhitespaceType.Whitespace_Preserve, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[40] = new TypeInfo( binder, _altova_ni_xs, "time", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_time.begin, _altova_mi_xs_altova_time.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.TimeFormatter );
			types[41] = new TypeInfo( binder, _altova_ni_xs, "token", _altova_ti_xs_altova_normalizedString, _altova_mi_xs_altova_token.begin, _altova_mi_xs_altova_token.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[42] = new TypeInfo( binder, _altova_ni_xs, "unsignedByte", _altova_ti_xs_altova_unsignedShort, _altova_mi_xs_altova_unsignedByte.begin, _altova_mi_xs_altova_unsignedByte.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "255", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[43] = new TypeInfo( binder, _altova_ni_xs, "unsignedInt", _altova_ti_xs_altova_unsignedLong, _altova_mi_xs_altova_unsignedInt.begin, _altova_mi_xs_altova_unsignedInt.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "4294967295", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[44] = new TypeInfo( binder, _altova_ni_xs, "unsignedLong", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_unsignedLong.begin, _altova_mi_xs_altova_unsignedLong.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "18446744073709551615", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[45] = new TypeInfo( binder, _altova_ni_xs, "unsignedShort", _altova_ti_xs_altova_unsignedInt, _altova_mi_xs_altova_unsignedShort.begin, _altova_mi_xs_altova_unsignedShort.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "65535", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );

			types[46] = new TypeInfo( binder, _altova_ni, "AssignType.datatype", _altova_ti_xs_altova_NMTOKEN, _altova_mi_altova_AssignType_datatype.begin, _altova_mi_altova_AssignType_datatype.end,  
				new FacetInfo[]
				{
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "replacechildren", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "firstchild", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "lastchild", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "previoussibling", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "nextsibling", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "replace", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "delete", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "addattribute", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[47] = new TypeInfo( binder, _altova_ni, "Binding.datatype", _altova_ti_xs_altova_NMTOKEN, _altova_mi_altova_Binding_datatype.begin, _altova_mi_altova_Binding_datatype.end,  
				new FacetInfo[]
				{
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "early", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "late", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[48] = new TypeInfo( binder, _altova_ni, "Boolean.datatype", _altova_ti_xs_altova_NMTOKENS, _altova_mi_altova_Boolean_datatype.begin, _altova_mi_altova_Boolean_datatype.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "enumeration", "true", 0 ), 
					new FacetInfo (null, "enumeration", "false", 0 ), 
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[49] = new TypeInfo( binder, _altova_ni, "CondLang.datatype", _altova_ti_xs_altova_string2, _altova_mi_altova_CondLang_datatype.begin, _altova_mi_altova_CondLang_datatype.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[50] = new TypeInfo( binder, _altova_ni, "Duration.datatype", _altova_ti_xs_altova_string2, _altova_mi_altova_Duration_datatype.begin, _altova_mi_altova_Duration_datatype.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\d*(\\.\\d+)?(ms|s|m|h|d)", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[51] = new TypeInfo( binder, _altova_ni, "EventType.datatype", _altova_ti_xs_altova_token, _altova_mi_altova_EventType_datatype.begin, _altova_mi_altova_EventType_datatype.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "(\\i|\\d|\\-)+(\\.(\\i|\\d|\\-)+)*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[52] = new TypeInfo( binder, _altova_ni, "EventTypes.datatype", _altova_ti_xs_altova_token, _altova_mi_altova_EventTypes_datatype.begin, _altova_mi_altova_EventTypes_datatype.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\.?\\*|(\\i|\\d|\\-)+(\\.(\\i|\\d|\\-)+)*(\\.\\*)?(\\s(\\i|\\d|\\-)+(\\.(\\i|\\d|\\-)+)*(\\.\\*)?)*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[53] = new TypeInfo( binder, _altova_ni, "Exmode.datatype", _altova_ti_xs_altova_NMTOKEN, _altova_mi_altova_Exmode_datatype.begin, _altova_mi_altova_Exmode_datatype.end,  
				new FacetInfo[]
				{
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "lax", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "strict", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[54] = new TypeInfo( binder, _altova_ni, "HistoryType.datatype", _altova_ti_xs_altova_string2, _altova_mi_altova_HistoryType_datatype.begin, _altova_mi_altova_HistoryType_datatype.end,  
				new FacetInfo[]
				{
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "shallow", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "deep", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[55] = new TypeInfo( binder, _altova_ni, "Integer.datatype", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_altova_Integer_datatype.begin, _altova_mi_altova_Integer_datatype.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[56] = new TypeInfo( binder, _altova_ni, "LocLang.datatype", _altova_ti_xs_altova_string2, _altova_mi_altova_LocLang_datatype.begin, _altova_mi_altova_LocLang_datatype.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[57] = new TypeInfo( binder, _altova_ni, "TransitionType.datatype", _altova_ti_xs_altova_NMTOKEN, _altova_mi_altova_TransitionType_datatype.begin, _altova_mi_altova_TransitionType_datatype.end,  
				new FacetInfo[]
				{
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "internal", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "external", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[58] = new TypeInfo( binder, _altova_ni, "URI.datatype", _altova_ti_xs_altova_anyURI, _altova_mi_altova_URI_datatype.begin, _altova_mi_altova_URI_datatype.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[59] = new TypeInfo( binder, _altova_ni, "ValueLang.datatype", _altova_ti_xs_altova_string2, _altova_mi_altova_ValueLang_datatype.begin, _altova_mi_altova_ValueLang_datatype.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[60] = new TypeInfo( binder, _altova_ni, "scxml.assign.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_assign_type.begin, _altova_mi_altova_scxml_assign_type.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[61] = new TypeInfo( binder, _altova_ni, "scxml.cancel.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_cancel_type.begin, _altova_mi_altova_scxml_cancel_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[62] = new TypeInfo( binder, _altova_ni, "scxml.content.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_content_type.begin, _altova_mi_altova_scxml_content_type.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[63] = new TypeInfo( binder, _altova_ni, "scxml.data.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_data_type.begin, _altova_mi_altova_scxml_data_type.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[64] = new TypeInfo( binder, _altova_ni, "scxml.datamodel.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_datamodel_type.begin, _altova_mi_altova_scxml_datamodel_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[65] = new TypeInfo( binder, _altova_ni, "scxml.donedata.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_donedata_type.begin, _altova_mi_altova_scxml_donedata_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[66] = new TypeInfo( binder, _altova_ni, "scxml.else.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_else_type.begin, _altova_mi_altova_scxml_else_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[67] = new TypeInfo( binder, _altova_ni, "scxml.elseif.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_elseif_type.begin, _altova_mi_altova_scxml_elseif_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[68] = new TypeInfo( binder, _altova_ni, "scxml.final.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_final_type.begin, _altova_mi_altova_scxml_final_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[69] = new TypeInfo( binder, _altova_ni, "scxml.finalize.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_finalize_type.begin, _altova_mi_altova_scxml_finalize_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[70] = new TypeInfo( binder, _altova_ni, "scxml.foreach.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_foreach_type.begin, _altova_mi_altova_scxml_foreach_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[71] = new TypeInfo( binder, _altova_ni, "scxml.history.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_history_type.begin, _altova_mi_altova_scxml_history_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[72] = new TypeInfo( binder, _altova_ni, "scxml.if.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_if_type.begin, _altova_mi_altova_scxml_if_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[73] = new TypeInfo( binder, _altova_ni, "scxml.initial.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_initial_type.begin, _altova_mi_altova_scxml_initial_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[74] = new TypeInfo( binder, _altova_ni, "scxml.invoke.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_invoke_type.begin, _altova_mi_altova_scxml_invoke_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[75] = new TypeInfo( binder, _altova_ni, "scxml.log.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_log_type.begin, _altova_mi_altova_scxml_log_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[76] = new TypeInfo( binder, _altova_ni, "scxml.onentry.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_onentry_type.begin, _altova_mi_altova_scxml_onentry_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[77] = new TypeInfo( binder, _altova_ni, "scxml.onexit.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_onexit_type.begin, _altova_mi_altova_scxml_onexit_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[78] = new TypeInfo( binder, _altova_ni, "scxml.parallel.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_parallel_type.begin, _altova_mi_altova_scxml_parallel_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[79] = new TypeInfo( binder, _altova_ni, "scxml.param.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_param_type.begin, _altova_mi_altova_scxml_param_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[80] = new TypeInfo( binder, _altova_ni, "scxml.raise.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_raise_type.begin, _altova_mi_altova_scxml_raise_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[81] = new TypeInfo( binder, _altova_ni, "scxml.script.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_script_type.begin, _altova_mi_altova_scxml_script_type.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[82] = new TypeInfo( binder, _altova_ni, "scxml.scxml.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_scxml_type.begin, _altova_mi_altova_scxml_scxml_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[83] = new TypeInfo( binder, _altova_ni, "scxml.send.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_send_type.begin, _altova_mi_altova_scxml_send_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[84] = new TypeInfo( binder, _altova_ni, "scxml.state.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_state_type.begin, _altova_mi_altova_scxml_state_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[85] = new TypeInfo( binder, _altova_ni, "scxml.transition.type", _altova_ti_xs_altova_anyType, _altova_mi_altova_scxml_transition_type.begin, _altova_mi_altova_scxml_transition_type.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[86] = new TypeInfo( binder, _altova_ni, "scxml", 0, _altova_mi_altova_scxml2.begin, _altova_mi_altova_scxml2.end,  null, 				WhitespaceType.Whitespace_Unknown );


		}

		public TypeInfo[] createTypes(InfoBinderInterface binder) {

			TypeInfo types[] = new TypeInfo[87];

			initTypes0(binder, types);
			
			return types;

		}
	}

	// Array of all members
	private static final MemberInfo members[] = new MemberInfoCreator().createMembers(binder);

	private static class MemberInfoCreator
	{
		private void initMembers0(InfoBinderInterface binder, MemberInfo[] members) {
			members[0] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_anyType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);

			members[1] = new MemberInfo (binder, "", "", _altova_ti_altova_scxml_assign_type, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);
			members[2] = new MemberInfo (binder, "", "location", _altova_ti_altova_scxml_assign_type, _altova_ti_altova_LocLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[3] = new MemberInfo (binder, "", "expr", _altova_ti_altova_scxml_assign_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[4] = new MemberInfo (binder, "", "type", _altova_ti_altova_scxml_assign_type, _altova_ti_altova_AssignType_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[5] = new MemberInfo (binder, "", "attr", _altova_ti_altova_scxml_assign_type, _altova_ti_xs_altova_NMTOKEN, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[6] = new MemberInfo (binder, "", "sendid", _altova_ti_altova_scxml_cancel_type, _altova_ti_xs_altova_IDREF, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[7] = new MemberInfo (binder, "", "sendidexpr", _altova_ti_altova_scxml_cancel_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[8] = new MemberInfo (binder, "", "", _altova_ti_altova_scxml_content_type, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);
			members[9] = new MemberInfo (binder, "", "expr", _altova_ti_altova_scxml_content_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[10] = new MemberInfo (binder, "", "", _altova_ti_altova_scxml_data_type, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);
			members[11] = new MemberInfo (binder, "", "id", _altova_ti_altova_scxml_data_type, _altova_ti_xs_altova_ID, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[12] = new MemberInfo (binder, "", "src", _altova_ti_altova_scxml_data_type, _altova_ti_altova_URI_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[13] = new MemberInfo (binder, "", "expr", _altova_ti_altova_scxml_data_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[14] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "data", _altova_ti_altova_scxml_datamodel_type, _altova_ti_altova_scxml_data_type, 0, 0, -1);

			members[15] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "content", _altova_ti_altova_scxml_donedata_type, _altova_ti_altova_scxml_content_type, 0, 0, 1);
			members[16] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "param", _altova_ti_altova_scxml_donedata_type, _altova_ti_altova_scxml_param_type, 0, 0, -1);

			members[17] = new MemberInfo (binder, "", "cond", _altova_ti_altova_scxml_elseif_type, _altova_ti_altova_CondLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[18] = new MemberInfo (binder, "", "id", _altova_ti_altova_scxml_final_type, _altova_ti_xs_altova_ID, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[19] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "onentry", _altova_ti_altova_scxml_final_type, _altova_ti_altova_scxml_onentry_type, 0, 0, -1);
			members[20] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "onexit", _altova_ti_altova_scxml_final_type, _altova_ti_altova_scxml_onexit_type, 0, 0, -1);
			members[21] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "donedata", _altova_ti_altova_scxml_final_type, _altova_ti_altova_scxml_donedata_type, 0, 0, -1);

			members[22] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "raise", _altova_ti_altova_scxml_finalize_type, _altova_ti_altova_scxml_raise_type, 0, 0, -1);
			members[23] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "if", _altova_ti_altova_scxml_finalize_type, _altova_ti_altova_scxml_if_type, 0, 0, -1);
			members[24] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "foreach", _altova_ti_altova_scxml_finalize_type, _altova_ti_altova_scxml_foreach_type, 0, 0, -1);
			members[25] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "send", _altova_ti_altova_scxml_finalize_type, _altova_ti_altova_scxml_send_type, 0, 0, -1);
			members[26] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "script", _altova_ti_altova_scxml_finalize_type, _altova_ti_altova_scxml_script_type, 0, 0, -1);
			members[27] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "assign", _altova_ti_altova_scxml_finalize_type, _altova_ti_altova_scxml_assign_type, 0, 0, -1);
			members[28] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "log", _altova_ti_altova_scxml_finalize_type, _altova_ti_altova_scxml_log_type, 0, 0, -1);
			members[29] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "cancel", _altova_ti_altova_scxml_finalize_type, _altova_ti_altova_scxml_cancel_type, 0, 0, -1);

			members[30] = new MemberInfo (binder, "", "array", _altova_ti_altova_scxml_foreach_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[31] = new MemberInfo (binder, "", "item", _altova_ti_altova_scxml_foreach_type, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[32] = new MemberInfo (binder, "", "index", _altova_ti_altova_scxml_foreach_type, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[33] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "raise", _altova_ti_altova_scxml_foreach_type, _altova_ti_altova_scxml_raise_type, 0, 0, -1);
			members[34] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "if", _altova_ti_altova_scxml_foreach_type, _altova_ti_altova_scxml_if_type, 0, 0, -1);
			members[35] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "foreach", _altova_ti_altova_scxml_foreach_type, _altova_ti_altova_scxml_foreach_type, 0, 0, -1);
			members[36] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "send", _altova_ti_altova_scxml_foreach_type, _altova_ti_altova_scxml_send_type, 0, 0, -1);
			members[37] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "script", _altova_ti_altova_scxml_foreach_type, _altova_ti_altova_scxml_script_type, 0, 0, -1);
			members[38] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "assign", _altova_ti_altova_scxml_foreach_type, _altova_ti_altova_scxml_assign_type, 0, 0, -1);
			members[39] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "log", _altova_ti_altova_scxml_foreach_type, _altova_ti_altova_scxml_log_type, 0, 0, -1);
			members[40] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "cancel", _altova_ti_altova_scxml_foreach_type, _altova_ti_altova_scxml_cancel_type, 0, 0, -1);

			members[41] = new MemberInfo (binder, "", "id", _altova_ti_altova_scxml_history_type, _altova_ti_xs_altova_ID, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[42] = new MemberInfo (binder, "", "type", _altova_ti_altova_scxml_history_type, _altova_ti_altova_HistoryType_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[43] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "transition", _altova_ti_altova_scxml_history_type, _altova_ti_altova_scxml_transition_type, 0, 1, 1);

			members[44] = new MemberInfo (binder, "", "cond", _altova_ti_altova_scxml_if_type, _altova_ti_altova_CondLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[45] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "raise", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_raise_type, 0, 0, -1);
			members[46] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "if", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_if_type, 0, 0, -1);
			members[47] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "foreach", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_foreach_type, 0, 0, -1);
			members[48] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "send", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_send_type, 0, 0, -1);
			members[49] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "script", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_script_type, 0, 0, -1);
			members[50] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "assign", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_assign_type, 0, 0, -1);
			members[51] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "log", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_log_type, 0, 0, -1);
			members[52] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "cancel", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_cancel_type, 0, 0, -1);
			members[53] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "elseif", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_elseif_type, 0, 0, 1);
			members[54] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "else", _altova_ti_altova_scxml_if_type, _altova_ti_altova_scxml_else_type, 0, 0, 1);

			members[55] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "transition", _altova_ti_altova_scxml_initial_type, _altova_ti_altova_scxml_transition_type, 0, 1, 1);

			members[56] = new MemberInfo (binder, "", "type", _altova_ti_altova_scxml_invoke_type, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[57] = new MemberInfo (binder, "", "typeexpr", _altova_ti_altova_scxml_invoke_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[58] = new MemberInfo (binder, "", "src", _altova_ti_altova_scxml_invoke_type, _altova_ti_altova_URI_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[59] = new MemberInfo (binder, "", "srcexpr", _altova_ti_altova_scxml_invoke_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[60] = new MemberInfo (binder, "", "id", _altova_ti_altova_scxml_invoke_type, _altova_ti_xs_altova_ID, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[61] = new MemberInfo (binder, "", "idlocation", _altova_ti_altova_scxml_invoke_type, _altova_ti_altova_LocLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[62] = new MemberInfo (binder, "", "namelist", _altova_ti_altova_scxml_invoke_type, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[63] = new MemberInfo (binder, "", "autoforward", _altova_ti_altova_scxml_invoke_type, _altova_ti_altova_Boolean_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[64] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "content", _altova_ti_altova_scxml_invoke_type, _altova_ti_altova_scxml_content_type, 0, 0, -1);
			members[65] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "param", _altova_ti_altova_scxml_invoke_type, _altova_ti_altova_scxml_param_type, 0, 0, -1);
			members[66] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "finalize", _altova_ti_altova_scxml_invoke_type, _altova_ti_altova_scxml_finalize_type, 0, 0, -1);

			members[67] = new MemberInfo (binder, "", "label", _altova_ti_altova_scxml_log_type, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[68] = new MemberInfo (binder, "", "expr", _altova_ti_altova_scxml_log_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[69] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "raise", _altova_ti_altova_scxml_onentry_type, _altova_ti_altova_scxml_raise_type, 0, 0, -1);
			members[70] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "if", _altova_ti_altova_scxml_onentry_type, _altova_ti_altova_scxml_if_type, 0, 0, -1);
			members[71] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "foreach", _altova_ti_altova_scxml_onentry_type, _altova_ti_altova_scxml_foreach_type, 0, 0, -1);
			members[72] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "send", _altova_ti_altova_scxml_onentry_type, _altova_ti_altova_scxml_send_type, 0, 0, -1);
			members[73] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "script", _altova_ti_altova_scxml_onentry_type, _altova_ti_altova_scxml_script_type, 0, 0, -1);
			members[74] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "assign", _altova_ti_altova_scxml_onentry_type, _altova_ti_altova_scxml_assign_type, 0, 0, -1);
			members[75] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "log", _altova_ti_altova_scxml_onentry_type, _altova_ti_altova_scxml_log_type, 0, 0, -1);
			members[76] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "cancel", _altova_ti_altova_scxml_onentry_type, _altova_ti_altova_scxml_cancel_type, 0, 0, -1);

			members[77] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "raise", _altova_ti_altova_scxml_onexit_type, _altova_ti_altova_scxml_raise_type, 0, 0, -1);
			members[78] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "if", _altova_ti_altova_scxml_onexit_type, _altova_ti_altova_scxml_if_type, 0, 0, -1);
			members[79] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "foreach", _altova_ti_altova_scxml_onexit_type, _altova_ti_altova_scxml_foreach_type, 0, 0, -1);
			members[80] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "send", _altova_ti_altova_scxml_onexit_type, _altova_ti_altova_scxml_send_type, 0, 0, -1);
			members[81] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "script", _altova_ti_altova_scxml_onexit_type, _altova_ti_altova_scxml_script_type, 0, 0, -1);
			members[82] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "assign", _altova_ti_altova_scxml_onexit_type, _altova_ti_altova_scxml_assign_type, 0, 0, -1);
			members[83] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "log", _altova_ti_altova_scxml_onexit_type, _altova_ti_altova_scxml_log_type, 0, 0, -1);
			members[84] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "cancel", _altova_ti_altova_scxml_onexit_type, _altova_ti_altova_scxml_cancel_type, 0, 0, -1);

			members[85] = new MemberInfo (binder, "", "id", _altova_ti_altova_scxml_parallel_type, _altova_ti_xs_altova_ID, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[86] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "onentry", _altova_ti_altova_scxml_parallel_type, _altova_ti_altova_scxml_onentry_type, 0, 0, -1);
			members[87] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "onexit", _altova_ti_altova_scxml_parallel_type, _altova_ti_altova_scxml_onexit_type, 0, 0, -1);
			members[88] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "transition", _altova_ti_altova_scxml_parallel_type, _altova_ti_altova_scxml_transition_type, 0, 0, -1);
			members[89] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "state", _altova_ti_altova_scxml_parallel_type, _altova_ti_altova_scxml_state_type, 0, 0, -1);
			members[90] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "parallel", _altova_ti_altova_scxml_parallel_type, _altova_ti_altova_scxml_parallel_type, 0, 0, -1);
			members[91] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "history", _altova_ti_altova_scxml_parallel_type, _altova_ti_altova_scxml_history_type, 0, 0, -1);
			members[92] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "datamodel", _altova_ti_altova_scxml_parallel_type, _altova_ti_altova_scxml_datamodel_type, 0, 0, -1);
			members[93] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "invoke", _altova_ti_altova_scxml_parallel_type, _altova_ti_altova_scxml_invoke_type, 0, 0, -1);

			members[94] = new MemberInfo (binder, "", "name", _altova_ti_altova_scxml_param_type, _altova_ti_xs_altova_NMTOKEN, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[95] = new MemberInfo (binder, "", "expr", _altova_ti_altova_scxml_param_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[96] = new MemberInfo (binder, "", "location", _altova_ti_altova_scxml_param_type, _altova_ti_altova_LocLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[97] = new MemberInfo (binder, "", "event", _altova_ti_altova_scxml_raise_type, _altova_ti_xs_altova_NMTOKEN, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[98] = new MemberInfo (binder, "", "", _altova_ti_altova_scxml_script_type, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);
			members[99] = new MemberInfo (binder, "", "src", _altova_ti_altova_scxml_script_type, _altova_ti_altova_URI_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);

			members[100] = new MemberInfo (binder, "", "initial", _altova_ti_altova_scxml_scxml_type, _altova_ti_xs_altova_IDREFS, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[101] = new MemberInfo (binder, "", "name", _altova_ti_altova_scxml_scxml_type, _altova_ti_xs_altova_NMTOKEN, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[102] = new MemberInfo (binder, "", "version", _altova_ti_altova_scxml_scxml_type, _altova_ti_xs_altova_decimal, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[103] = new MemberInfo (binder, "", "datamodel", _altova_ti_altova_scxml_scxml_type, _altova_ti_xs_altova_NMTOKEN, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[104] = new MemberInfo (binder, "", "binding", _altova_ti_altova_scxml_scxml_type, _altova_ti_altova_Binding_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[105] = new MemberInfo (binder, "", "exmode", _altova_ti_altova_scxml_scxml_type, _altova_ti_altova_Exmode_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[106] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "state", _altova_ti_altova_scxml_scxml_type, _altova_ti_altova_scxml_state_type, 0, 0, -1);
			members[107] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "parallel", _altova_ti_altova_scxml_scxml_type, _altova_ti_altova_scxml_parallel_type, 0, 0, -1);
			members[108] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "final", _altova_ti_altova_scxml_scxml_type, _altova_ti_altova_scxml_final_type, 0, 0, -1);
			members[109] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "datamodel", _altova_ti_altova_scxml_scxml_type, _altova_ti_altova_scxml_datamodel_type, 0, 0, -1);
			members[110] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "script", _altova_ti_altova_scxml_scxml_type, _altova_ti_altova_scxml_script_type, 0, 0, -1);

			members[111] = new MemberInfo (binder, "", "event", _altova_ti_altova_scxml_send_type, _altova_ti_altova_EventType_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[112] = new MemberInfo (binder, "", "eventexpr", _altova_ti_altova_scxml_send_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[113] = new MemberInfo (binder, "", "target", _altova_ti_altova_scxml_send_type, _altova_ti_altova_URI_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[114] = new MemberInfo (binder, "", "targetexpr", _altova_ti_altova_scxml_send_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[115] = new MemberInfo (binder, "", "type", _altova_ti_altova_scxml_send_type, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[116] = new MemberInfo (binder, "", "typeexpr", _altova_ti_altova_scxml_send_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[117] = new MemberInfo (binder, "", "id", _altova_ti_altova_scxml_send_type, _altova_ti_xs_altova_ID, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[118] = new MemberInfo (binder, "", "idlocation", _altova_ti_altova_scxml_send_type, _altova_ti_altova_LocLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[119] = new MemberInfo (binder, "", "delay", _altova_ti_altova_scxml_send_type, _altova_ti_altova_Duration_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[120] = new MemberInfo (binder, "", "delayexpr", _altova_ti_altova_scxml_send_type, _altova_ti_altova_ValueLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[121] = new MemberInfo (binder, "", "namelist", _altova_ti_altova_scxml_send_type, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[122] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "content", _altova_ti_altova_scxml_send_type, _altova_ti_altova_scxml_content_type, 0, 0, -1);
			members[123] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "param", _altova_ti_altova_scxml_send_type, _altova_ti_altova_scxml_param_type, 0, 0, -1);

			members[124] = new MemberInfo (binder, "", "id", _altova_ti_altova_scxml_state_type, _altova_ti_xs_altova_ID, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[125] = new MemberInfo (binder, "", "initial", _altova_ti_altova_scxml_state_type, _altova_ti_xs_altova_IDREFS, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[126] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "onentry", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_onentry_type, 0, 0, -1);
			members[127] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "onexit", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_onexit_type, 0, 0, -1);
			members[128] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "transition", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_transition_type, 0, 0, -1);
			members[129] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "initial", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_initial_type, 0, 0, -1);
			members[130] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "state", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_state_type, 0, 0, -1);
			members[131] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "parallel", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_parallel_type, 0, 0, -1);
			members[132] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "final", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_final_type, 0, 0, -1);
			members[133] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "history", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_history_type, 0, 0, -1);
			members[134] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "datamodel", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_datamodel_type, 0, 0, -1);
			members[135] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "invoke", _altova_ti_altova_scxml_state_type, _altova_ti_altova_scxml_invoke_type, 0, 0, -1);

			members[136] = new MemberInfo (binder, "", "event", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_EventTypes_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[137] = new MemberInfo (binder, "", "cond", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_CondLang_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[138] = new MemberInfo (binder, "", "target", _altova_ti_altova_scxml_transition_type, _altova_ti_xs_altova_IDREFS, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[139] = new MemberInfo (binder, "", "type", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_TransitionType_datatype, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[140] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "raise", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_scxml_raise_type, 0, 0, -1);
			members[141] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "if", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_scxml_if_type, 0, 0, -1);
			members[142] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "foreach", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_scxml_foreach_type, 0, 0, -1);
			members[143] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "send", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_scxml_send_type, 0, 0, -1);
			members[144] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "script", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_scxml_script_type, 0, 0, -1);
			members[145] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "assign", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_scxml_assign_type, 0, 0, -1);
			members[146] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "log", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_scxml_log_type, 0, 0, -1);
			members[147] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "cancel", _altova_ti_altova_scxml_transition_type, _altova_ti_altova_scxml_cancel_type, 0, 0, -1);

			members[148] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "assign", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_assign_type, 0, 0, 1);
			members[149] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "cancel", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_cancel_type, 0, 0, 1);
			members[150] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "content", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_content_type, 0, 0, 1);
			members[151] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "data", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_data_type, 0, 0, 1);
			members[152] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "datamodel", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_datamodel_type, 0, 0, 1);
			members[153] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "donedata", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_donedata_type, 0, 0, 1);
			members[154] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "else", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_else_type, 0, 0, 1);
			members[155] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "elseif", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_elseif_type, 0, 0, 1);
			members[156] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "final", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_final_type, 0, 0, 1);
			members[157] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "finalize", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_finalize_type, 0, 0, 1);
			members[158] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "foreach", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_foreach_type, 0, 0, 1);
			members[159] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "history", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_history_type, 0, 0, 1);
			members[160] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "if", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_if_type, 0, 0, 1);
			members[161] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "initial", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_initial_type, 0, 0, 1);
			members[162] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "invoke", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_invoke_type, 0, 0, 1);
			members[163] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "log", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_log_type, 0, 0, 1);
			members[164] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "onentry", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_onentry_type, 0, 0, 1);
			members[165] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "onexit", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_onexit_type, 0, 0, 1);
			members[166] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "parallel", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_parallel_type, 0, 0, 1);
			members[167] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "param", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_param_type, 0, 0, 1);
			members[168] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "raise", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_raise_type, 0, 0, 1);
			members[169] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "script", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_script_type, 0, 0, 1);
			members[170] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "scxml", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_scxml_type, 0, 0, 1);
			members[171] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "send", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_send_type, 0, 0, 1);
			members[172] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "state", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_state_type, 0, 0, 1);
			members[173] = new MemberInfo (binder, "http://www.w3.org/2005/07/scxml", "transition", _altova_ti_altova_scxml2, _altova_ti_altova_scxml_transition_type, 0, 0, 1);

		}

		public MemberInfo[] createMembers(InfoBinderInterface binder) {

			MemberInfo members[] = new MemberInfo[174];

			initMembers0(binder, members);
			
			return members;

		}
	}
}
